# Generated by Django 2.2.10 on 2020-11-24 09:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresumes',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userresumes',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userresumes',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='userresumes',
            name='name',
        ),
        migrations.AddField(
            model_name='userresumes',
            name='pages',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='userresumes',
            name='pdf',
            field=models.FileField(default=django.utils.timezone.now, upload_to='UploadedPDFs/', verbose_name='Upload Resumes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userresumes',
            name='tables',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='userresumes',
            name='title',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
