# Generated by Django 2.2.10 on 2020-12-03 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0002_auto_20201124_1054'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserResumes',
            new_name='UserPDF',
        ),
    ]
